### PR TITLE
fix: styling main element in IE 11

### PR DESCRIPTION
**Pull request by mmktomato**
The styling about `.page-content` is not affected in IE 11 because the default value of `display` of `main` element is 'inline'. (It's 'block' in Chrome 64.)
It will be fixed by adding 'display: block;' to `main` element.

### CODE REVIEW

**Comment by DirtyF** [comment]
@jekyllbot: :shipit:

**Comment by DirtyF** [comment]
@jekyllbot: 🚢 +minor

**Comment by parkr** [comment]
@jekyllbot: merge +fix

**Comment by mmktomato** [comment]
Thx for reviewing and merging !

**Pull request merged**
