### PR TITLE
Add stackoverflow to social media list

### PR DESCRIPTION
**Pull request by hszhakka**

### CODE REVIEW

**Comment by hszhakka** [comment]
> README

OK! I have updated README now.

**Comment by ashmaroli** [comment]
@DirtyF What's the policy regarding support for social media icons in Minima..?
I see that there are some more PRs open that add social media icons..

**Comment by ashmaroli** [comment]
Duplicate #368

**Comment by ashmaroli** [comment]
Prior art: #353

**Comment by DirtyF** [comment]
@ashmaroli I think we have enough default icons now, given the Stackoverflow SVG was already in the repo, this one is legit.

**Comment by DirtyF** [comment]
@jekyllbot: merge +minor

**Pull request merged**
