### PR TITLE
Introduce "Dark Minima" skin

### LINKED ISSUE #143: Is there a "Dark Minima" theme out there?
I really like the features and layout of the minima theme, but wish it could be inverted on the colors.  Is there a minima based theme out there that is dark?

### PR DESCRIPTION
**Pull request by xxyzz**
Resolves #143 

Color palette based on https://primer.style/ (ref: https://github.com/jekyll/minima/issues/143#issuecomment-435308808)

**update:** jekyll-minima-dark-skin

### CODE REVIEW

**Comment by ashmaroli** [comment]
@xxyzz Thank you for this proposal.

@DirtyF Would this be better if it were a skin..?
```yaml
minima:
  skin: dark # or default (light)
```

**Comment by ashmaroli** [comment]
@xxyzz Are you still interested in getting this pull request merged to `master`..?

**Comment by xxyzz** [comment]
Of cause, I have checked out this branch from the latest master branch. I'm trying to adjust some colors.

**Comment by DirtyF** [comment]
Note: Primer colors are defined in https://github.com/primer/primitives/blob/master/primitives/colors.json

Example implementation: https://github.com/primer/components/blob/master/src/theme.js

**Comment by ashmaroli** [comment]
Hello everyone, since Minima's *classic* skin is primarily based on grayscale tones, I have modified this proposal to be based on grayscale tones, but from the opposite end of the spectrum.

I have also temporarily changed the skin on the preview deploy, so that you all can easily take a look at the current state by visiting: https://deploy-preview-335--jekyll-minima.netlify.com/

*(The deploy will be switched back to the default skin prior to merging..)*

**Comment by ashmaroli** [comment]
Why does this need documentation..?

**Comment by DirtyF** [comment]
How do people know they can switch to Dark Mode?

**Comment by xxyzz** [comment]
The current README file already has a section explains how to set skin: https://github.com/jekyll/minima#skins

**Comment by ashmaroli** [comment]
> The current README file already has a section explains how to set skin

Yes. But ideally, it should also have a sub-section listing the available skins..

**Comment by ashmaroli** [comment]
Thank you @xxyzz 
@jekyllbot: merge +minor

**Pull request merged**
