### PR TITLE
Add skin classic-dark

### PR DESCRIPTION
**Pull request by jeremyhalin**
Hi,
Here is my proposal for a `classic-dark` skin.
What do you think?

Preview classic-dark skin

### CODE REVIEW

**Comment by ashmaroli** [comment]
Thank you very much @jeremyhalin. If you don't mind, I'm going to leave some comments below. You're free to consider / reject them..

- I think the name `classic-dark` is verbose. How about just `dark`?
- I personally feel the current background is too black. How about `#181818` to reduce the contrast?
- I see that borders for the social-icons are now `transparent`. Why?
- Once #452 gets merged, I think you'll have more control over the tweaking.. Will you be able to revisit this once that gets merged..?

**Comment by jeremyhalin** [comment]
- Sure `dark` is a better name.
- For the black background, I used `#121212` from [Dark theme - Material Design](https://material.io/design/color/dark-theme.html#properties)
- I made borders transparent to hide it honestly, personal taste I guess so maybe I could set a white color with less opacity
- sure thing, when #452 will get merged?

**Comment by jeremyhalin** [comment]
I see there is already an ongoing work about a dark theme #335

**Comment by ashmaroli** [comment]
> set a white color with less opacity

I'd prefer setting a solid grey that matches the resulting color instead of a white with an alpha channel.


> when #452 will get merged?

Can't really say.. It is up for review from one of the other maintainers.

**Comment by ashmaroli** [comment]
> already an ongoing work about a dark theme

Yes. But it hasn't been revisited.. So can't really say if it'll come up to speed..

**Comment by DirtyF** [comment]
Duplicate of #335

**Pull request closed without merging**
