### PR TITLE
Remove RSS icon from the social media list

### LINKED ISSUE #457: Remove the subscribe button on the home page
https://github.com/jekyll/minima/blob/d4bfaf248cf9632731b618dca4ce540975f23b20/_layouts/home.html#L59

Maybe this subscribe button can be removed since it's redundant because that the link to `feed.xml` revealed too on the social media list.

### PR DESCRIPTION
**Pull request by hszhakka**
Prior art: #464
Fixes #457

### CODE REVIEW

**Comment by ashmaroli** [comment]
Thank you for submitting this, @hszhakka. But there's a small problem now: A visitor currently at one of the post-page needs to go to the home page to navigate the site's feed (or enter the URL manually).

**Comment by hszhakka** [comment]
> Thank you for submitting this, @hszhakka. But there's a small problem now: A visitor currently at one of the post-page needs to go to the home page to navigate to the site's feed (or enter the URL manually).

Now I have moved the subscribe button to the footer:

Screenshot 2020-02-17 at 11 15 18 PM

**Comment by ashmaroli** [comment]
Updated screenshot:
footer-rss

**Comment by DirtyF** [comment]
@jekyllbot: merge +minor

**Pull request merged**
