### PR TITLE
Remove /feed.xml

### PR DESCRIPTION
**Pull request by alzeih**
- /feed.xml link is broken
- minima doesn't generate any feed out of the box
- minima doesn't depend on jekyll-feed
- minima is "supposed to be minimal"

See #129 and #98.

### CODE REVIEW

**Comment by pathawks** [comment]
:+1:

**Comment by alzeih** [comment]
It's also 
- not documented in the README.md
- not tested for in Travis CI
- broken in the theme preview at https://jekyll.github.io/minima/

**Comment by ashawley** [comment]
I'd support removing the feed in a new major release, but would propose making the graceful fix in #129 for new users of the current version.

**Comment by DirtyF** [comment]
> minima doesn't depend on jekyll-feed

fixed in #183

**Comment by ashawley** [comment]
Thanks for merging #141, the social links changes, before this one.  Apologies for it causing conflicts with feed.xml removal.

**Comment by alzeih** [comment]
Rebased after #141 , no problems

**Comment by alzeih** [comment]
> Fine by me, even If I can't hardly imagine a minimal blog theme without a feed.

Jekyll is also great for static websites generally, which have no need for a feed.

Unfortunately, finding out how many Jekyll users use `jekyll-feed` deliberately is a wicked problem, since it's included by default with `jekyll new`.

**Comment by DirtyF** [comment]
Link to feed has been fixed in #183

**Pull request closed without merging**
