### PR TITLE
Change RSS references

### PR DESCRIPTION
**Pull request by Cj-Malone**
The jekyll-feed plugin uses Atom not RSS.

But I've removed the format completely as I don't think people care. I also fixed the mime type, which should help with some parsing issues.

### CODE REVIEW

**Comment by pathawks** [comment]
This should probably just be removed, as Minima does not generate _any_ feed out of the box.

**Comment by Cj-Malone** [comment]
@pathawks I've just seen https://github.com/jekyll/minima/issues/98 too, I've added the checks that @alzeih recommended. I think it's best to have the feed references added by default in minima for users that opt to use `jekyll-feed`. It's best for it to be done right here rather than an implementation per site.

**Comment by aterenin** [comment]
Might I suggest using a SVG icon instead of the word `Subscribe`? I think it would look a bit cleaner and more in line with the overall theme (similar to GitHub, Twitter icons). See `http://avt.im` for an example. I am happy to make a PR if people agree.

**Comment by ashmaroli** [comment]
> using a SVG icon instead of the word Subscribe?

That would appear less like a link. A bit too minimalistic?
On the other hand, some minimal text with the icon would look fine IMO..

**Comment by alzeih** [comment]
@Cj-Malone thanks! Jekyll seems to have renamed `site.gems` to `site.plugins` (https://github.com/jekyll/jekyll/issues/4509 , https://github.com/jekyll/jekyll/pull/5130 , https://github.com/jekyll/jekyll/pull/6045 ) so maybe replace `site.gems` with `site.plugins` ?

As Jekyll plugins can alternatively be enabled in Bundler (https://jekyllrb.com/docs/plugins/), the plugin may be enabled and not be listed in `site.plugins`. I haven't found a way to query gems in group `:jekyll_plugins` from liquid yet. Does someone know a way?

**Comment by ashmaroli** [comment]
> Jekyll seems to have renamed `site.gems` to `site.plugins`

Yes. But its only been deprecated in Jekyll. There still may be sites out there using `Jekyll 3.5.x` but with `gems:` in their config file..
So its bit of a fragmentation issue now.

But if Team Minima decides to include this feature as part of Minima 3.0, then its probably safe to disregard Jekyll-3.5.x users still on the `gems:` config

**Comment by DirtyF** [comment]
> As Jekyll plugins can alternatively be enabled in Bundler (https://jekyllrb.com/docs/plugins/), the plugin may be enabled and not be listed in site.plugins.

True. Closing them as this workaround does not address the entire issue.

**Comment by ashawley** [comment]
Ok, I didn't realize it was impossible to sense plugins in Jekyll in all situations.  Seems that the safest way to fix #98 is to break the feed by deleting it.

**Pull request closed without merging**
