### PR TITLE
Add jekyll-seo-tag dependency

### LINKED ISSUE #138: Add Open Graph tags

### PR DESCRIPTION
**Pull request by DirtyF**
From Jeyll 3.5, gem-based themes can declare plugin dependencies.

Let's improve SEO for all `minima` users.

fix #138 #96

### CODE REVIEW

**Comment by ashawley** [comment]
For completeness, list it as a plugin in the config?

**Comment by ashmaroli** [comment]
> For completeness, list it as a plugin in the config?

@ashawley this isn't necessary, Jekyll 3.5 will look into the `.gemspec` and automatically `require` the seo plugin.

**Comment by ashmaroli** [comment]
@DirtyF Can we remove the whitespace *around* the `<link>` tags?
Also, it'd be nice if the `README` mentioned this enhancement and advising users there's *no need* for additionally adding the seo-plugin to their config file / Gemfile

**Comment by ashawley** [comment]
> this isn't necessary, Jekyll 3.5 will look into the .gemspec and automatically require the seo plugin.

I recognize it's not necessary.  Just seems worth documenting in the default config

**Comment by ashmaroli** [comment]
> seems worth documenting in the default config, as well as the README

I'm fine with appending to the README but on the fence about documenting in the config file because IMO it wouldn't matter if users add the seo-plugin to their config file because Ruby _may not_ call `require` on the same plugin twice (currently demonstrated with a plugin added to both `:jekyll_plugins` in Gemfile **and** `plugins` in config file.)

**Comment by ashawley** [comment]
> it wouldn't matter if users add the seo-plugin to their config file because Ruby may not call `require` on the same plugin twice

Are you saying that plugins listed under `plugins` in the config automatically get pulled in by Ruby?  I didn't think it did that.  It only gives an error.  Maybe I'm missing something.

**Comment by ashmaroli** [comment]
> Are you saying that plugins listed under plugins in the config automatically get pulled in by Ruby?

Plugins listed under `plugins:` in the config file get pulled in by Ruby if the plugin-gem is available for loading. Jekyll raises errors under following situations:
  - The plugin is not installed on the local system
  - When there's a `Gemfile`, and the installed plugin is not included in it.
The error in this case is due to Bundler selectively masking the installed gems based on the Gemfile, ergo to Jekyll, your plugin-gem is not installed if its not in the `Gemfile`

GitHub Pages ignores a Gemfile, so it loads plugins based on the config file alone. Once it gets upgraded to Jekyll 3.5, it will additionally load `whitelisted` plugins from a theme's `.gemspec`

**Comment by ashawley** [comment]
> When there's a Gemfile, and the installed plugin is not included in it.

Ah, this is the piece I was missing.  Thanks.

**Comment by DirtyF** [comment]
fix #96

**Comment by DirtyF** [comment]
@benbalter For now It works locally with GitHub Pages gem when pointing to minima `master` branch but not on GitHub Pages, build failled.

**Comment by benbalter** [comment]
@DirtyF if we cut a new version of `minima` and bump it in the GitHub Pages Gem, it should build properly (lest any user could add a runtime dependency to a theme and whitelist any gem for use on GitHub Pages).

**Comment by ashmaroli** [comment]
@DirtyF Since you did not invoke JekyllBot to merge this, you'll have to manually update `History.markdown` to document this enhancement.

**Pull request merged**
