### PR TITLE
HTML escape author in posts

### PR DESCRIPTION
**Pull request by ashawley**

### CODE REVIEW

**Comment by benbalter** [comment]
@ashawley thanks for this. Can you provide some more context on what you're trying to do here?

**Comment by ashawley** [comment]
Someone had two author's names on a post, and I noticed that the ampersand wasn't escaped.

**Comment by DirtyF** [comment]
Should @jekyll/minima support multi-author posts and allow to maintain a list of authors?

**Comment by ashawley** [comment]
> support multi-author posts and allow to maintain a list of authors?

That'd be cool.  Wouldn't that need to be agreed upon and implemented in Jekyll, generally?

**Comment by DirtyF** [comment]
@ashawley I was just thinking of specifying authors in `_config.yml` or in a _`data/authors.yml` and make use of this in the template.

**Pull request merged**
