### PR TITLE
fix home layout HTML error #279

### PR DESCRIPTION
**Pull request by ettingshausen**
fix home layout HTML error #279

### CODE REVIEW

**Comment by DirtyF** [comment]
What actuel problem does is solve? What HTML error are you referencing?

generated-html

**Comment by ettingshausen** [comment]
It was a HTML validator error. Actually the hyperlink works. I described at issue #279

**Comment by DirtyF** [comment]
Closing as there is currently no validation error related to this: https://validator.w3.org/nu/?doc=https%3A%2F%2Fjekyll.github.io%2Fminima%2F

**Comment by ettingshausen** [comment]
@DirtyF 
It is the source code.
https://github.com/jekyll/minima/blob/280deb6d21f9d91f29af928b9134d8b78f05046e/_layouts/home.html#L31

**Comment by DirtyF** [comment]
@ettingshausen I know, but we'll stick to double quotes in Liquid templates and that's perfectly fine.
Feel free to use single quotes if that better fits your workflow. We validate final HTML output.

**Pull request closed without merging**
