### PR TITLE
Release gem from 2.5-stable via GitHub Actions

### PR DESCRIPTION
**Pull request by ashmaroli**
Build and release **minima-2.5.2** via GitHub Actions

### CODE REVIEW

**Comment by ashmaroli** [comment]
@jekyllbot: merge +dev

**Comment by ashmaroli** [comment]
@parkr Requesting that `${{ secrets.RUBYGEMS_GEM_PUSH_API_KEY }}` be defined for the `jekyll/minima` repository.

**Comment by parkr** [comment]
> @parkr Requesting that `${{ secrets.RUBYGEMS_GEM_PUSH_API_KEY }}` be defined for the `jekyll/minima` repository.

Done!

**Comment by ashmaroli** [comment]
Thanks @parkr 
Minima 2.5.2 [published successfully](https://rubygems.org/gems/minima/versions/2.5.2) :)

**Pull request merged**
