### PR TITLE
Support pagination through posts in home layout

### LINKED ISSUE #159: Only show a certain number of posts per page.
It seems like the index/home will continue to show all posts. What happens when a user hits 100? 1000? Even as static HTML, it is a lot to load, especially for mobile. 

Can we limit each page to like 50 or 100? Could we make it configurable?

### PR DESCRIPTION
**Pull request by ashmaroli**
Prior art: #150 
Resolves #159 

## Pager samples
(total of 3 pages)
First page
Second page
Last page

### CODE REVIEW

**Comment by ashmaroli** [comment]
> I'd prefer browsing with "older posts" / "newer posts" links than numbers

Using just numbers have the followings pros:
- Minimal :stuck_out_tongue: 
- Reasonably same-sized pager buttons.
- *Easier* integration in localized sites. Numbers are *mostly the same* in latin-based languages.

**Comment by DirtyF** [comment]
@ashmaroli as I said personal nit 😉 

@jekyllbot: merge +minor

**Comment by hszhakka** [comment]
A long-awaited improvement, but don't you need to add `jekyll-pagination` in `gemspec`?

**Comment by ashmaroli** [comment]
> don't you need to add `jekyll-pagination` in `gemspec`?

No. Pagination is an opt-in feature.
The config setting `paginate` is needed for `jekyll-paginate` plugin (supported on GitHub Pages). I don't know if `jekyll-pagination` accepts the same config.

Users wishing to add pagination should do the needful at their end. Minima 3.0 just *supports* using it out-of-the box.

**Pull request merged**
