### PR TITLE
fix: make page.list_title optional

### LINKED ISSUE #196: Remove the default "Posts" of "page.list_title" in the home layout
Is there a reason for this default?

I think it makes no sense to have a "Posts" as headline if the posts are the only content of the page.
e.g. http://blog.sharaal.de/
 
I think there are several approaches to improve it:
* Remove the default
* Make it configurable 
* Depending on the content (only if there is a content, show the "Posts" as headline between content and the posts)

At least it would be nice not to need to overwrite the home layout only to prevent this default.

### PR DESCRIPTION
**Pull request by jekyllbot**
fix #196 

```text
fix: make page.list_title optional
```

### CODE REVIEW

**Comment by kriation** [comment]
@jekyllbot @DirtyF - Can this be merged? It's a great fix, and can easily be merged with master.

**Comment by ashmaroli** [comment]
@kriation Once this change has been merged, it'd mean that "list title" `"Posts"` will be rendered only if it has been explicitly defined in the front matter.

As it is, this heading is **only rendered if there are one or more posts in the site.**

I would like to know more details behind your request to have this merged.

**Comment by kriation** [comment]
The intent of this is to remove 'Posts' as the default, and only set list title if configured. This is based on feedback from the community through issue #196

**Comment by corazza** [comment]
hey, why hasn't this been merged?

**Comment by hszhakka** [comment]
> hey, why hasn't this been merged?

It seems that this PR has been merged into the [`minima-next`](https://github.com/jekyll/minima/tree/minima-next) branch.

**Comment by ashmaroli** [comment]
Thank you @DirtyF 
@jekyllbot: merge +minor

**Pull request merged**
