### PR TITLE
Showing the modified date of posts and the copyright

### PR DESCRIPTION
**Pull request by alexddhuang**

### CODE REVIEW

**Comment by ashmaroli** [comment]
@DirtyF Is the *modified-date` part of this PR acceptable..?

**Comment by ashmaroli** [comment]
@alexddhuang Do you wish to continue working on this contribution and have it merged..?
If yes, please remove the copyright-feature from this branch.

**Comment by hszhakka** [comment]
> @alexddhuang Do you wish to continue working on this contribution and have it merged..?
> If yes, please remove the copyright-feature from this branch.

😀Maybe you can merge my PR #432, which implements the same *modified-date* feature, but not includes copyright-feature.

**Comment by ashmaroli** [comment]
> which implements the same _modified-date_ feature, but not includes copyright-feature.

We'll give @alexddhuang a chance to get back to us and update this branch. If we don't get a response from him in the next 7 days, this will be closed.

**Pull request closed without merging**
