### PR TITLE
fixed Flash Of Unstyled SVG

### PR DESCRIPTION
**Pull request by Strangehill**
When CSS is disabled or fails to load SVG images scale and take up the entire viewport width.

For more on this: [SVG Style Inheritance and the ‘Flash Of Unstyled SVG’](https://sarasoueidan.com/blog/svg-style-inheritance-and-FOUSVG/)

### CODE REVIEW

**Comment by Strangehill** [comment]
solves #14

**Comment by DirtyF** [comment]
@Strangehill you added the first part (specify the width and height in the SVG) but not the second part: you didn't define a relative size on the SVG selector in the CSS in case it needs to scale. Is it intentional ?

**Comment by Strangehill** [comment]
Correct. The original design didn't have relative sizes on any of the SVG selectors, and I didn't add any myself.

**Comment by benbalter** [comment]
@jglovier any strong feelings either way here?

**Comment by Strangehill** [comment]
A scenario where css stylesheets break letting the svgs loose:
Using https everywhere and visiting a site using `{{ site.github.url }}` like this: `<link rel="stylesheet" href="{{ "/css/main.css" | prepend: site.github.url }}">`
This can make the styles on many a jekyll site break because for the time being site.github.url returns http and not https and this creates a 'mixed content' problem for the browser.
See this issue comment [github/pages-gem/issues/238](https://github.com/github/pages-gem/issues/238#issue-140203297)

**Comment by benbalter** [comment]
LGTM.

**Comment by benbalter** [comment]
@jekyllbot: merge +minor

**Comment by benbalter** [comment]
Thanks @Strangehill! Been noticing this on a few sites myself!

**Comment by jglovier** [comment]
@Strangehill thanks for the PR! Nice improvement. :boom: :heart:

**Pull request merged**
