### PR TITLE
Stick footer for short posts

### LINKED ISSUE #222: Footer should be at the bottom of the screen
For long posts, I have to scroll down to see the footer, and the page ends right after -- there is no unwanted space below the footer. This is good.

For short posts, the footer is right below the post and there is a lot of space below the footer, between it and the end of the screen. This is bad. The footer should be at the bottom of the screen in this case.

For a default theme, there are a lot of style issues... but I am learning a lot about CSS :)

### PR DESCRIPTION
**Pull request by DirtyF**
Fix #222 

minima-stick-footer

### CODE REVIEW

**Comment by ashmaroli** [comment]
LGTM! :+1:

**Comment by montyf** [comment]
Why not apply `flex: 1;` to `.post-content` as well?

I just tried this solution and it worked for my blog! It's much simpler than the previous solution I had and doesn't require knowing the size of the footer beforehand.

**Comment by parkr** [comment]
Nice! I have never seen the flex properties. Are they cross-browser compatible?

**Comment by DirtyF** [comment]
@parkr https://caniuse.com/#feat=flexbox

**Pull request merged**
