### PR TITLE
Add `auto` skin which honors the `prefers-color-scheme` media query

### PR DESCRIPTION
**Pull request by sandervoerman**
This is a follow-up to https://github.com/jekyll/minima/pull/594, and adds the following changes:

- the `auto` skin renders in light or dark mode depending on the `prefers-color-scheme` media query;
- code has been refactored so that `auto` and `classic` share the same color definitions for light mode, and `auto` and `dark` for dark mode.

Screenshots:

auto skin, on Windows 10 in light mode:

jlight

auto skin, on Windows 10 in dark mode:
jdark

### CODE REVIEW

**Comment by ashmaroli** [comment]
Couple of comments:
- The name `classic` was selected to denote legacy appearance (Minima 2 n older). Having it *switch* to a dark mode doesn't sit nicely with me. How about --- `auto`, `classic`, `dark`..?
- The table details for the new variants include duplicate info. IMO, you could move that to an anchored section below the table and link to the section in the description cells.

**Comment by sandervoerman** [comment]
>     * The name `classic` was selected to denote legacy appearance (Minima 2 n older). Having it _switch_ to a dark mode doesn't sit nicely with me. How about --- `auto`, `classic`, `dark`..?
 
Sure! What would become the default skin, then? `auto` or `classic`?

**Comment by ashmaroli** [comment]
> What would become the default skin, then? `auto` or `classic`?

`classic` for now since it is probably what consumers of this theme via `jekyll-remote-theme` plugin expects. Lets not shock them right away.

Once we come up with a way to demo the skins *on every OS / browser*, we may / can switch to `auto` being the default, or may not, at all. However, if we decide to cut a new release before that, it'll remain `classic`.
IMO, this shouldn't be a one-person decision.

**Comment by ashmaroli** [comment]
Um.. To reduce duplication or conflict from #594 getting merged before this, lets not make changes to the README on this branch just yet.. Let the document be finalized there first.

**Comment by sandervoerman** [comment]
ok sorry! 😅

**Comment by DoodlesEpic** [comment]
Closes #660 
Any reason why this hasn't gotten any updates?

**Comment by sandervoerman** [comment]
> Any reason why this hasn't gotten any updates?

I think this PR is waiting for #594 which in turn is waiting for review...

**Comment by mattr-** [comment]
#594 has been merged, so this PR can be updated against the lateest master and be moved out of draft mode when it's ready.

**Comment by sandervoerman** [comment]
@mattr- Ready now, let me know if you need anything else.

**Review by mattr- — APPROVED** [review]

**Comment by mattr-** [comment]
@jekyllbot: merge +minor

**Pull request merged**
