### PR TITLE
Basic i18n

### PR DESCRIPTION
**Pull request by oncleben31**
minima is a real simple template. To avoid surcharging the includes or layouts just to change the 2 text strings used and the date format, I've put some settings in the _config.yml file.

If the _config.file are not set, default values are used to be consistent with the current template without my PR.

Example of new settings to have the minima in French:
```yml
posts_title: "Article"
subscribe_RSS: "S'abonner aux flux "
post_date_format: "%d/%m/%Y" 
```

### CODE REVIEW

**Comment by oncleben31** [comment]
I think I should move all the _config.yml comments linked to my PR in the documentation like done with Disqus and Google Analytics.
Any advice on that ?

**Comment by ashmaroli** [comment]
First and foremost, you'll have rebase this branch. Run the following:
```
git fetch upstream master
git rebase upstream/master
```

I've modified the README.md in PR-43, around the two sections you mentioned. This will raise conflicts for you if you add in a section on **I18n** right away, if that gets merged first. 
If you're experienced at resolving conflicts in git, you can proceed, else I recommend waiting for that to get merged and then syncing this branch to update.

**Comment by oncleben31** [comment]
I think I've done something wrong with the rebase. There is still a commit not related to my branch.
I've transfered the instructions to the README.md to be more consistent with the other settings.

I'm wondering if this is the best way to do the basic i18n. Perhaps we can use a way similar to what is explain on the [Sylvain Durang's blog in "Translation of website elements" section](https://www.sylvaindurand.org/making-jekyll-multilingual/). He uses a dictionary, eventually stored in data folder, to store different language localization.

@ashmaroli what is your point of view ?

**Comment by ashmaroli** [comment]
this branch in its current state cannot be considered for merge as it reverts many changes made to the `minima:master` branch

But now that most of the extra commits have been removed, I looked into what exactly is it that you are proposing. Unfortunately, you're only changing the date formats and a few strings ( `posts_title` doesnt make any sense how its related to i18n. )

I dont think *Minima* needs to have this provided out-of-the-box, so the overall verdict for this PR, from me is :-1: sorry.

--
P.S. A few asides:
- I like the link to Sylvain Durang's blog post. I've not read through in detail, but a cursory read-through tells me that he has outlined the concept well. Thanks for that. 
- If you still want this PR to be considered by the lead maintainers, you'll have to clean this branch further. My suggestion would be to delete this branch locally and start-over from scratch:
  - Move to your `master` branch first:   `git checkout master` 
  - (Force) Delete the PR branch ***locally***:     `git branch -D basic-i18n`
  - Update local `master` branch:    `git pull upstream master`
  - ***Re-create*** `basic-i18n` branch **from `master`** : `git checkout -b basic-i18n`
  - *Redo* the changes related to this PR and commit to branch.
  - (Force) Update the PR branch at GitHub: `git push -f origin basic-i18n`

Good Luck!

**Comment by DirtyF** [comment]
@oncleben31 i18n is crucial and users should be able to switch easily to their default langage when using Jekyll. I feel like this should be handled in a plugin or upstream and Minima could benefit from it and provide a few default languages, as this is the default theme that many people will take as an example. As a comparison Middleman handles i18n keys (https://middlemanapp.com/advanced/localization/#toc)

Maybe @jekyll/core can share insights and a more detailed answer.

**Comment by oncleben31** [comment]
I've not give up. I've just clean my master fork and branch. 
I will try to do it a better way waiting having the tool or framework in Jekyll core.
I'm sure plugin already exist but as the easiest way for a beginner to host their new Jekyll/Minima blog is on Github Pages, I want to do it without any plugin.

**Pull request closed without merging**
