### PR TITLE
Use icons from Font Awesome to show social links

### PR DESCRIPTION
**Pull request by zivhub**
The target of this PR is to use icons from [Font Awesome](https://fontawesome.com/) as icons in social links. This has the following advantages:

1. **The code is more concise.** `assets/minima-social-icons.svg` is not necessary anymore.
2. **Be more flexible.** Minima no longer needs to consider all social platforms in advance. If a user wants to add a new social link, he/she only needs to add a new item under the `site.minima.social_links` variable in his/her repo and he/she can choose the icon he/she likes. For example,

   ```yml
   minima:
     social_links:
       - title: Instagram
         url: https://www.instagram.com/jekyll/
         icon: fab fa-instagram
   ```

### CODE REVIEW

**Comment by zivhub** [comment]
Related: #577 #556 #302

**Comment by Dylan-Bollard** [comment]
This is a great addition. I was about to create a guide for people on how to manipulate assets/minima-social-icons.svg. This is far better.

**Comment by zivhub** [comment]
> This is a great addition. I was about to create a guide for people on how to manipulate assets/minima-social-icons.svg. This is far better.
> 
> Also, I've using Iconify. Free source. Not sure if Font Awesome is 100% free.

Font Awesome is not 100% free; some icons can only be used in the Pro version. 

I need to think about which icon framework to use. It should preferably meet these conditions:

1. There are rich icons.
2. Easy to use.
3. Free.
4. Popular enough.

**Comment by mattr-** [comment]
Hi! :wave: I'd prefer to avoid a dependency on an icon font for this theme if possible, so this pull request will be closed. Thank you for taking the time to contribute. :heart:

**Pull request closed without merging**
