### PR TITLE
Bigger font-size for h1 in content

### LINKED ISSUE #113: h2 has a larger font than h1 in Chrome
I see in layout.scss that Minima is forcing `.post-content h2` to 32px. However, I don't see a similar rule for `.post-content h1`. This means that by default, in Chrome, `h2` elements are larger than `h1`s, because Chrome's default size for `h1` is 24px. Is this intentional?

### PR DESCRIPTION
**Pull request by DirtyF**
fix #113

### CODE REVIEW

**Comment by ashmaroli** [comment]
its not just for posts. the `page` layout uses `.post-content` as well

**Comment by DirtyF** [comment]
@ashmaroli I don't know if it's a good idea to encourage many h1 per page (I am already sceptical for posts)

**Comment by ashmaroli** [comment]
> I don't know if it's a good idea to encourage many h1 per page

Its not. The idea even is frowned upon by the community. But regular users need not know about such conventions.

Btw, I was hinting at this PR's Title. This PR actually applies to both `post` layout and `page` layout as they both reference a `<div class="post-content">`

**Comment by antgel** [comment]
> The idea even is frowned upon by the community. But regular users need not know about such conventions.

Where does that leave this PR? :)

**Comment by dvhart** [comment]
As a new user, I just ran into this myself today and eventually made my way here. Nothing in my reading of the jekyll docs about writing posts or in the markdown syntax hinted that there should not be more than # or === header per document. If there is some thing that documents this as "bad" other than tribal knowledge, I missed it. This seems like a reasonable fix to push to help "regular users" like myself avoid this issue.

**Comment by dvhart** [comment]
Perhaps the issue is with the mapping of a MD H1 header # or === to an HTML <h1> tag? Since we don't use an MD header marker for the title in the pages themselves (that's in the filename or the front matter as I understand it), then perhaps Jekyll should be mapping MD HN header tags to <hN+1> in html. (MD H1 becomes <h2> in HTML). This would effectively reserve <h1> for the title by mapping MD tags to <h2> and lower. Perhaps it's too late for that given the number users now dependent on the existing behavior.

**Comment by ashmaroli** [comment]
@DirtyF So many merge commits!! :roll_eyes: 
I'd just squash all those superfluous commits into one single merge commit..

**Comment by DirtyF** [comment]
fixed in #273

**Pull request closed without merging**
