### PR TITLE
Add tumblr social link

### PR DESCRIPTION
**Pull request by laxa88**
Preview:

minima-tumblr

Tumblr logo SVG taken from: https://www.svgrepo.com/svg/141732/tumblr-logo

Note: I resized the SVG to 60% to match the size of other social icons, using online tool: https://aydos.com/svgedit/

### CODE REVIEW

**Review by MichaelCurrin — APPROVED** [review]

**Comment by MichaelCurrin** [comment]
Needs update from master but looks good

**Comment by ashmaroli** [comment]
Thanks, but we won't be adding any more social media icons to this theme.

**Comment by laxa88** [comment]
@ashmaroli Just curious, I don't see any harm in adding this (and other missing social links); is there a reason why?

**Comment by ashmaroli** [comment]
Because Minima was originally intended to be a minimal *get-started-with-jekyll* theme that provides the bare essentials to help novice Jekyll users get onboard with the program and focus on writing content. *Minimal not only in the aesthetics but also in the features*.
Somewhere along the dev road, the above intention got diluted to result in a minimal theme that would encourage users to customize the theme, and in the process, get acquainted with managing a theme with Jekyll.

Social media platforms are many in number. We too thought there's isn't harm in adding support for some more but then soon realized that supporting each and every popular platform is going to get unwieldy and go against the *minimal* theme idea.

**Pull request closed without merging**
