### PR TITLE
Make docs consistent with code

### PR DESCRIPTION
**Pull request by jamiepinheiro**
Fixes typo mentioned in https://github.com/jekyll/minima/issues/645.

### CODE REVIEW

**Comment by jamiepinheiro** [comment]
@mattr- could I get a review on this?

**Comment by mattr-** [comment]
Yes! Sorry! Been busy with other things.

**Review by mattr- — APPROVED** [review]
LGTM. Thank you! Sorry for taking so long on this.

**Comment by mattr-** [comment]
@jekyllbot: merge +docs

**Pull request merged**
