### PR TITLE
Close #55: Improve mobile user experience

### LINKED ISSUE #55: Improve loading time
There are some optimization identified by [Google insights](https://developers.google.com/speed/pagespeed/insights/)

Is it possible to improve the score ?

Currently:
-   Mobile
  - loading time 90/100
  - user experience 90/100
-   PC 96/100

### PR DESCRIPTION
**Pull request by zdroid**
This should do the trick. Please rewiew it. :rocket:

### CODE REVIEW

**Comment by oncleben31** [comment]
With this PR tested on my blog the PageSpeed Insights score is now 100/100 (previously 90/100)

**Comment by zdroid** [comment]
Thanks @oncleben31. I'm happy to hear that. :smile:

@pathawks Care to review this?

**Comment by benbalter** [comment]
@jekyllbot: merge +minor.

**Comment by benbalter** [comment]
Thanks @zdroid! Sorry for the delay here.

**Pull request merged**
