### PR TITLE
Improve the readablility of blockquotes

### PR DESCRIPTION
**Pull request by hszhakka**
The narrow letter-spacing hurts my eyes. 

Setting the font style of blockquotes to *italic* may erase the different styles between emphasis and normal text in the blockquote.

Before:

Screenshot 2020-02-25 at 8 34 34 PM

After:

Screenshot 2020-02-25 at 8 33 37 PM

### CODE REVIEW

**Comment by hszhakka** [comment]
> 👎 for removing italics

Reasons?

**Comment by hszhakka** [comment]
Well, after googling, I know the reason: In the typography of the Latin alphabet, the Italic type is often used to indicate quotations.

Sorry, English is not my mother language.

**Comment by hszhakka** [comment]
However, we need a way to handle italics within italics. Here I adopt the MLA style, which specifies a switch back to roman type. @DirtyF

**Comment by ashmaroli** [comment]
@hszhakka Please update the blockquote in the demo post to contain `<i/`>` and `<em/>` (separated by a couple or more words).

**Comment by hszhakka** [comment]
> @hszhakka Please update the blockquote in the demo post to contain `<i/>` and `<em/>` (separated by a couple or more words).

OK, I have added. The final display:

Screenshot 2020-02-26 at 1 50 09 PM

**Comment by DirtyF** [comment]
@jekyllbot: merge +minor

**Pull request merged**
