### PR TITLE
WIP: Minima next

### PR DESCRIPTION
**Pull request by DirtyF**
This is a proposal to a slightly revisited styles for minima by @jglovier 

minima-next

minima-next-styes

### CODE REVIEW

**Comment by jglovier** [comment]
@DirtyF thanks for keeping this going! There appear to be some styling inconsistencies with my mocks. Can't remember if I just never finished working on the branch or if they got introduced elsewhere, but I'll add some commits and post new screenshots to tidy it up. ✨

**Comment by jglovier** [comment]
Also, what's the timeline here? I'd really like to push it a little further like adding a built in color theming generator (thinking of just using some CSS variables and allowing users to set a base hex color in the config file), etc.

**Comment by ajbozdar** [comment]
What is the possible release day of Minima 3.0?

**Comment by DirtyF** [comment]
@ajbozdar No timeline here, @jglovier will work on this whenever he wants.

**Comment by jglovier** [comment]
As for an update, I'm taking some time off in January and plan to get this across the finish line then.

**Comment by hszhakka** [comment]
> As for an update, I'm taking some time off in January and plan to get this across the finish line then.

😂@jglovier  Did you forget this progress?

**Comment by DirtyF** [comment]
@hszhakka It's OK for people to change focus, life happens. feel free to build upon this work if you feel ike to 😉

**Comment by hszhakka** [comment]
> @hszhakka It's OK for people to change focus, life happens. feel free to build upon this work if you feel ike to 😉

No one can decide to merge this branch to master except for @jglovier ? This style looks pretty for me, very exciting to see it appears in Minima 3.0. Or can I make a PR based on this work?

**Comment by ashmaroli** [comment]
> merge this branch to master except for @jglovier? Or can I make a PR based on this work?

Technically, any maintainer can merge any branch. But in this case, the changes are huge. So, it is not an easy task.

You're free to use parts of the code here as a starting point for your PR. But ensure that you credit the original author properly in the commit message.
This attribution is not just for @jglovier. It is to be followed for every author whose unattributed code is being used in a pull request without their explicit consent.

**Pull request closed without merging**
