### PR TITLE
Honor DNT for Google Analytics

### PR DESCRIPTION
**Pull request by MikkCZ**

### CODE REVIEW

**Comment by MikkCZ** [comment]
@DirtyF r?

**Comment by MikkCZ** [comment]
@pathawks I am not sure if a template should enforce this. IMO it should definitely be configurable. The decision is on the project maintainers. If the decision is made, I will be more than happy to add the config entry to enable it by default.

**Comment by pathawks** [comment]
I am asking you why any site would not want this. If there isn’t a good reason, why add a configuration option?

**Comment by MikkCZ** [comment]
If you think so, I can update the PR of course. Should I?

**Comment by MikkCZ** [comment]
I have updated the patch.

**Comment by DirtyF** [comment]
@jekyllbot: merge +minor

**Comment by DirtyF** [comment]
@jekyllbot: merge +minor

**Pull request merged**
