### PR TITLE
add feature

### PR DESCRIPTION
**Pull request by TakreemAkhter**
reading time indicator for posts

### CODE REVIEW

**Comment by sziv2p** [comment]
1. You didn't provide the `reading-time.html` file.
2. This feature might be out of the scope of this theme.

**Comment by TakreemAkhter** [comment]
I agree with your second point but it is a good addition and promotes user engagement.

**Comment by sziv2p** [comment]
> I agree with your second point but it is a good addition and promotes user engagement.

It depends on what the maintainers @ashmaroli @DirtyF think. I have also submitted some small improvements before, but they have all been rejected because they are beyond the scope of this theme.

**Comment by TakreemAkhter** [comment]
Thanks

**Pull request closed without merging**
