### PR TITLE
Document changes in 2.2.0

### LINKED ISSUE #215: A file was included in `/_layouts/default.html` that is a symlink or does not exist in your `_includes` directory
My github page, that built successfully over 2 weeks ago, now is failing with the following error:

> The page build failed for the `master` branch with the following error:
> 
> A file was included in `/_layouts/default.html` that is a symlink or does not exist in your `_includes` directory. For more information, see https://help.github.com/articles/page-build-failed-file-is-a-symlink/.
> 
> For information on troubleshooting Jekyll see:
> 
>   https://help.github.com/articles/troubleshooting-jekyll-builds

Could you suggest how to resolve this?
Do I need to update something or add some files?
Is it a bug in minima theme?

### PR DESCRIPTION
**Pull request by DirtyF**
People upgrading from previous versions can face errors at build 😢 

fix #215

### CODE REVIEW

**Comment by parkr** [comment]
Can we refactor to allow for both? This is very unfortunate :(

**Comment by ashawley** [comment]
This change was released in v2.2.0 a few months ago.

Looks like gh-pages moved from v2.1 to v2.4 for minima a few weeks ago:

https://github.com/github/pages-gem/releases/tag/v179

Is this happening often?

**Comment by DirtyF** [comment]
The build error will occur for people with a customized footer that references former includes  for social links. We reintroduced these includes in #217 to avoid that. To use the new social links, people will need to update their `footer.html` accordingly.

**Comment by DirtyF** [comment]
We reintroduce missing includes in #217 to avoid the build error.

**Pull request closed without merging**
