### PR TITLE
Use absolute_url filter for disqus

### LINKED ISSUE #65: disqus url ignore baseurl
`this.page.url` and `this.page.identifier` should use `url + baseurl` instead of only `url`.

### PR DESCRIPTION
**Pull request by DirtyF**
Fix #65 

cc @jekyll/minima

### CODE REVIEW

**Comment by ashmaroli** [comment]
wont `relative_url` work in this context?

**Comment by benbalter** [comment]
@jekyllbot: merge +minor

**Comment by benbalter** [comment]
Thanks @DirtyF!

**Comment by mdoliwa** [comment]
How can I update my github-pages blog with this fix?

rubygems.org has an old version, so I changed gem source to this repo in my Gemfile with:

`gem 'minima', '~> 2.0', :git => 'https://github.com/jekyll/minima.git' `

I push it to github but disqus still does not work, and looking into source code I still get:

```
    var disqus_config = function () {
      this.page.url = '/2016/11/09/hello-world.html';
      this.page.identifier = '/2016/11/09/hello-world.html';
    };
```
What am I doing wrong?

**Comment by ashmaroli** [comment]
@mdoliwa, it *could be* because Github Pages use a different version of Jekyll called `gem "github-pages"` and that uses Rubygems version of Minima.. irrespective of what you specify in your Gemfile.

**Comment by jenzz** [comment]
Sorry to bring this issue up again, but the absolute URL still does not resolve for me.

I'm seeing the same code generated as @mdoliwa using **minima 2.1.0** at master@bcabdbd.

**Comment by jenzz** [comment]
Sorry to bring this issue up again, but the absolute URL still does not resolve for me.

I'm seeing the same code generated as @mdoliwa using minima 2.1.0 at master@bcabdbd.

**Comment by mdoliwa** [comment]
@jenzz Make sure you have `url` and `baseurl` fields setup correctly in your `_config.yml`

**Comment by jenzz** [comment]
@mdoliwa Oops. I was indeed not setting the `url` param correctly. It's working now. Thanks a lot!

**Pull request merged**
