### PR TITLE
Use date_format if set in configuration

### PR DESCRIPTION
**Pull request by ward**
If it is not set, fall back to the previous default.

### CODE REVIEW

**Comment by ward** [comment]
See issue https://github.com/jekyll/minima/issues/69

**Comment by DirtyF** [comment]
@ward LGTM, would you mind adding an example section in the README file?

**Comment by parkr** [comment]
I might do `site.minima.date_format`. Starting to get more concerned about overlapping parameters.

**Comment by ashmaroli** [comment]
> I might do site.minima.date_format. Starting to get more concerned about overlapping parameters.

I have written a plugin [`jekyll-data`](https://github.com/ashmaroli/jekyll-data) that reads data files in theme gems and also provides a `theme` liquid-drop as an alias for site.data.[theme-name].
If @jekyll/minima is fine with `require`-ing that plugin, then we can ship a `minima.yml` inside 
`<minima-root>/_data` that contains *minima*-specific configurations.

```html
<!-- 'theme.date_format' is an alias for 'site.data.minima.date_format' -->
{% assign date_format = theme.date_format %}
{% if site.date_format %}
  <span class="post-meta">{{ post.date | date: site.date_format }}</span>
{% else %}
  <span class="post-meta">{{ post.date | date: "%b %-d, %Y" }}</span>
{% endif %}
```

**Comment by oncleben31** [comment]
Don't know if there is any performance impact. I though that using the `default` liquid filter is better than the `if ... else ... endif`

Something like
```
{% assign date_format = theme.date_format | default:  "%b %-d, %Y" %}
<span class="post-meta">{{ post.date | date: date_format }}
````

Is there any pros and cons?

**Comment by ward** [comment]
* Documentation: Adding a line in customization seems like it should be enough, correct?
* Naming: I tried a quick search before deciding date_format to see if there was some jekyll default for this, but did not find anything. Found that quite surprising actually, I imagine plenty of people would want to change this, regardless of what theme they use. (Though I admit on older jekyll versions I did it by editing the theme files directly)
* `default` vs `if`: I did (and do) not know enough about liquid. If `default` is more performant, then it is the preferred choice indeed.

**Comment by DirtyF** [comment]
@ward  

yeah, based on what Parkr recommends, I was thinking of something like:

## Change default date format

You can do so by specifying `theme.minima.dateformat` in `_config.yml`:

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
site:
  minima:
    date_format: "%b %-d, %Y"

I would even add the above snippet by default  in the `_config.yml` and use it right away in the theme, if you ask me, so you can simplify the layout.

**Comment by benbalter** [comment]
If it's a site configuration flag, I don't understand why it'd be in a data file (content), rather than `_config.yml` (site configuration)

**Comment by ashmaroli** [comment]
> If it's a site configuration flag, I don't understand why it'd be in a data file (content), rather than _config.yml (site configuration)

because *to me*, `site.minima.myvariable` is not site-configuration, but rather, a theme-configuration; and jekyll-data plugin expects to find theme configuration in `/_data` dir.

I may be wrong in thinking that data files can blur the lines between content and configuration, but its worth a shot. :smiley:

**Comment by DirtyF** [comment]
@ward Thanks!

**Comment by ward** [comment]
Any update on when this will be merged in?

**Comment by ashmaroli** [comment]
FWIW, the most recent version of `jekyll-data` plugin reads a `_config.yml` within theme-gem. This would allow theme developers to ship theme specific default configuration within the theme-gem..
```yaml
# <minima-gem>/_config.yml
#
# ** currently works only when using `jekyll-data` plugin` **
#
# minima-specific DEFAULTS (currently set using the `default` liquid-filter)
# will be specified below and accessed via `{{ site.minima.myvariable }}`
#
minima:
  lang: "en"
  date_format: "%b %-d, %Y"
```

**Comment by benbalter** [comment]
@jekyllbot: merge +minor.

Thanks @ward! Sorry for the delay in getting this merged.

**Comment by Sathors** [comment]
Would it be possible to have a release that includes this change?

Thanks.

**Comment by DirtyF** [comment]
@ward @Sathors FYI if you want to benefit from the latest changes on the theme you can always point to the `master`branch of this repo meanwhile.

```yaml
gem "minima", :github => "jekyll/minima", :branch => "master"
```

**Comment by Sathors** [comment]
Thanks for the tips, I knew about it, but it is more maintenance burden.

More than anything, it is because the Readme does indicate this option, so one is expecting it to be present in the release.

Thank you nonetheless.

**Pull request merged**
