### PR TITLE
Fix html proofer errors

### PR DESCRIPTION
**Pull request by oncleben31**
When using travis-ci with the basics tests found in Jekyll documentation, the tests raised errors with minima template:
*    when `site.email` is empty in `_config.yml` there is an error in footer.html
*    The `<a href="#">` tag raises an error in header.html

I'm not a CSS and HTML specialist but from what I've read on internet href="#" is a bad use of the tag.

Hope my fix is correct.

### CODE REVIEW

**Comment by ashmaroli** [comment]
Hi.. may I ask you to amend the typo in the latest commit message?

**Comment by oncleben31** [comment]
Done

**Comment by parkr** [comment]
LGTM. @jglovier, any strong feelings either way>?

**Comment by parkr** [comment]
@jekyllbot: merge +bug

**Pull request merged**
